// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAczETUaeH27Nzt4zsIa5iR5VUzrDNzAdQ',
    appId: '1:835773367066:android:7e5d0d911e1c562d5222a3',
    messagingSenderId: '835773367066',
    projectId: 'house-of-pianos',
    storageBucket: 'house-of-pianos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFttyViJ6rtB7tiCyHEVMwZHJibMbaOTA',
    appId: '1:835773367066:ios:28edf44d2d3d3dec5222a3',
    messagingSenderId: '835773367066',
    projectId: 'house-of-pianos',
    storageBucket: 'house-of-pianos.appspot.com',
    androidClientId: '835773367066-209f7n62tmb38knlc6nejqtp7b9kbfft.apps.googleusercontent.com',
    iosClientId: '835773367066-082aobfhk8mp33kb0dh99amnbfkv9spf.apps.googleusercontent.com',
    iosBundleId: 'com.pianohouse',
  );
}
